{
  config,
  pkgs,
  ...
}:
{
  home.packages =
    with pkgs;
    [
      # keep-sorted start

      acpi
      age
      bandwhich
      binutils
      black
      bloom
      broot
      cachix
      caligula
      cargo
      cargo-binstall
      cargo-release
      chrpath
      cmake
      cmeel
      # cmake-format
      cntr
      comma
      dcfldd
      deadnix
      # devenv
      dfc
      dig
      docker-compose
      dockgen
      doggo
      dos2unix
      dua
      dust
      erdtree
      evince
      #eww-wayland
      ffmpeg
      file
      fishPlugins.bass
      formatjson5
      #font-awesome
      fuzzel
      gersemi
      ghostscript
      git-extras
      git-fork-clone
      git-objects-cache
      git-statuses
      gnumake
      gnupg
      # himalaya
      htop
      httpie
      hugo
      hwloc
      iftop
      imv
      inetutils
      iotop
      jless
      jq
      just
      keep-sorted
      khal
      khard
      killall
      less
      lsof
      lurk
      md5cron
      mdbook
      mdcat
      minicom
      mosh
      mpc
      mypy
      nb
      ncdu
      ninja
      #nix-du
      nix-diff
      nix-output-monitor
      nix-tree
      nix-update
      nixd
      nixfmt
      nixook
      nixpkgs-review
      nmap
      #noto-fonts-emoji
      nurl
      openldap
      openssl
      pandoc
      pciutils
      pipewire
      pipx
      pkg-config
      plantuml
      playerctl
      pmapnitor
      pratches
      pre-commit
      pre-commit-sort
      prek
      pulseaudio
      pwgen
      rofimoji
      rbw
      rosdep
      ruff
      rustc # nor pre-commit
      rustscan
      sccache
      sd
      shellcheck
      slurp
      #snapcast
      sops
      sqlite
      ssh-to-age
      statix
      strace
      #sway
      tailstamp
      tdf
      templup
      tig
      toml-sort
      tree
      tree-sitter
      typst
      typstyle
      unzip
      usbutils
      uv
      #ventoy  # TODO: https://github.com/ventoy/Ventoy/issues/3224
      vdirsyncer
      watchexec
      weechat
      wev
      wget
      xkcdpass
      yq
      yt-dlp
      zfs
      #zola
      # keep-sorted end
    ]
    ++ [
      (python3.withPackages (
        ps: with ps; [
          # keep-sorted start
          django
          httpx
          ipython
          jinja2
          ldap3
          numpy
          pandas
          pandocfilters
          pip
          pyarrow
          pyyaml
          tabulate
          tomlkit
          tqdm
          wand
          wheel
          # keep-sorted end
        ]
      ))
    ]
    ++ lib.optionals config.nim-home.gui [
      # keep-sorted start
      #wireplumber
      wl-clipboard
      wtype
      libreoffice
      xwayland-satellite
      zathura
      wdisplays
      brightnessctl
      cage
      d-spy
      gparted
      grim
      iosevka
      kcov
      kdePackages.kolourpaint
      mesa-demos
      meshlab
      meld
      mpv
      niri
      pdfarranger
      pwvucontrol
      rofi-rbw
      signal-desktop
      swaybg
      vlc
      vscode-fhs
      swaylock
      pdfpc
      pinentry-qt
      nitrogen
      kdePackages.okular
      iosevka-aile
      iosevka-etoile
      iosevka-term
      zeal
      # keep-sorted end
    ];

}
