# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3b47c651-c55f-4384-8c84-ea8fd535c7d2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-79f51bc8-4cb7-4dde-820b-1e4403cb8a25".device = "/dev/disk/by-uuid/79f51bc8-4cb7-4dde-820b-1e4403cb8a25";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2EFE-CDA0";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/eafbd18d-fb85-4978-84e0-a22a95027cdf"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
