[project]
name = "kal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Guilhem Saurel", email = "guilhem.saurel@laas.fr" }
]
requires-python = ">=3.14"
dependencies = [
    "eclipse-zenoh>=1.10.0",
    "gpio>=1.0.1",
]

[project.scripts]
kal = "kal:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=9.16.1",
]
