{
  config,
  lib,
  ...
}:

{
  imports = [ ./options.nix ];
  # DO NOT EDIT THIS FILE AFTER INSTALLATION of a machine
  # Otherwise your system might not boot because of missing partitions / filesystems
  boot.loader.grub.efiSupport = lib.mkDefault true;
  boot.loader.grub.efiInstallAsRemovable = lib.mkDefault true;

  disko.devices = {
    disk = {
      main = {
        type = "disk";
        content = {
          type = "gpt";
          partitions = {

            "ESP" = {
              size = config.nim-disko.bootSize;
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "nofail" ];
              };
              priority = 10;
            };

            "swap" = {
              size = config.nim-disko.swapSize;
              content = {
                type = "swap";
                discardPolicy = "both";
              };
              priority = 20;
            };

            "root" = {
              size = "100%";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
              };
              priority = 30;
            };

          };
        };
      };
    };
  };
}
