theme = "zenburnt"

[editor]
cursorline = true
cursorcolumn = true
auto-pairs = false

[keys.normal]
# hjkl → ctsr
c = "move_char_left"
t = "move_line_down"
s = "move_line_up"
r = "move_char_right"

# ctsr → hjkl
h = "change_selection"
j = "find_till_char"
k = "select_regex"
l = "replace"

# [keys.select]
# # hjkl → ctsr
# c = "move_char_left"
# t = "move_line_down"
# s = "move_line_up"
# r = "move_char_right"

[keys.insert]
# tab to esc
tab = "normal_mode"
