theme = "zenburnt"

[editor]
auto-pairs = false
cursorcolumn = true
cursorline = true

[keys.insert]
# tab to esc
tab = "normal_mode"

[keys.normal]
# hjkl → ctsr
c = "move_char_left"
# ctsr → hjkl
h = "change_selection"
j = "find_till_char"
k = "select_regex"
l = "replace"
r = "move_char_right"
s = "move_line_up"
t = "move_line_down"
