name: "Build home-manager"

on: push

jobs:
  hm:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: cachix/cachix-action@v14
        with:
          name: nim65s-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - run: nix build .config/home-manager/upepesanke#homeConfigurations.gsaurel.activationPackage
      - run: nix build .config/home-manager/yupa#homeConfigurations.nim.activationPackage
      - run: nix build nixos/loon#nixosConfigurations.loon.config.system.build.toplevel
