name: "Build home-manager"

on: push

jobs:
  hm:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: cachix/cachix-action@v14
        with:
          name: nim65s-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix run home-manager/master -- build --flake .config/home-manager/upepesanke#gsaurel
