name: "Build home-manager"

on: push

jobs:
  hm:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: cachix/cachix-action@v14
        with:
          name: nim65s-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community,nim65s-nur,rycee
      #- run: nix build --accept-flake-config .#homeConfigurations."gsaurel@asahi".activationPackage
      #- run: nix build --accept-flake-config .#homeConfigurations."gsaurel@upepesanke".activationPackage
      #- run: nix build --accept-flake-config .#homeConfigurations."nim@yupa".activationPackage
      #- run: nix build --accept-flake-config .#nixosConfigurations.loon.config.system.build.toplevel
      #- run: nix build --accept-flake-config .#nixosConfigurations.hattorixos.config.system.build.toplevel
      #- run: nix build --accept-flake-config .#nixosConfigurations.fix.config.system.build.toplevel
