name: "Build home-manager"
on: push
jobs:
  hm:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: nim65s
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community,nim65s-nur,rycee
      - run: nix build .#homeConfigurations."gsaurel@asahi".activationPackage
      - run: nix build .#homeConfigurations."gsaurel@upepesanke".activationPackage
      - run: nix build .#homeConfigurations."nim@yupa".activationPackage
      - run: nix build .#nixosConfigurations.loon.config.system.build.toplevel
    #- run: nix build .#nixosConfigurations.hattorixos.config.system.build.toplevel
    #- run: nix build .#nixosConfigurations.fix.config.system.build.toplevel
